### ISSUE TITLE
About the fully and densely annotated dataset for evalution

### ISSUE THREAD

**Issue by shudct** [batra-mlp-lab/object-proposals#39]
Hi, all
The paper of this project has metioned that there is a fully and densely annotated dataset for evalution. I find under the /evaluation-metrics/data/ there are two groundtruth files of pascal_voc. However, the two one is the same. I wonder how I can get the new annoationed groundtruth of the pascal voc dataset. 
Thanks !

**Comment by aroma123** [comment]
Hi,
The dataset is available on the project webpage. You would find the link in the paper.
Thanks!
